# Generated by Django 3.2.16 on 2025-03-01 12:39

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='Название корма')),
                ('time', models.TimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'График кормления',
                'verbose_name_plural': 'Графики кормления',
            },
        ),
        migrations.CreateModel(
            name='HealthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Анализ здоровья',
                'verbose_name_plural': 'Анализы здоровья',
            },
        ),
        migrations.CreateModel(
            name='PetSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='Название вакцины')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Прививка',
                'verbose_name_plural': 'Прививки',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('birth_date', models.DateField(validators=[core.validators.real_age], verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('Самец', 'Самец'), ('Самка', 'Самка')], default=('Самец', 'Самец'), max_length=20, verbose_name='Пол')),
                ('weight', models.IntegerField(default=10, verbose_name='Вес')),
                ('height', models.IntegerField(default=10, verbose_name='Размер')),
                ('image', models.ImageField(blank=True, default='pets/cat_profile.webp', upload_to='pets/profile_photo', verbose_name='Картинка')),
                ('characteristic', models.TextField(blank=True, null=True, verbose_name='Особенности')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='pets.breed', verbose_name='Порода')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='pets.petspecies', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Домашнее животное',
                'verbose_name_plural': 'Домашние животные',
                'ordering': ('id',),
            },
        ),
    ]
