# Generated by Django 3.2.16 on 2025-03-01 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets.vaccination', verbose_name='Прививка'),
        ),
        migrations.AddField(
            model_name='healthanalysis',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='pets.pet', verbose_name='Домашнее животное'),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feeding', to='pets.pet', verbose_name='Домашнее животное'),
        ),
        migrations.AddField(
            model_name='breed',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='pets.petspecies'),
        ),
    ]
