# Generated by Django 3.2.16 on 2025-03-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='pets.pet', verbose_name='Прививка'),
        ),
    ]
