# Generated by Django 3.2.16 on 2025-03-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20250301_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feedingschedule',
            name='food_name',
            field=models.ForeignKey(default='Не указано', on_delete=django.db.models.deletion.CASCADE, related_name='food', to='pets.food', verbose_name='Название корма'),
        ),
    ]
