# Generated by Django 3.2.16 on 2025-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20250301_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingschedule',
            name='time',
            field=models.TimeField(default=0, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='Не указано', max_length=100),
        ),
    ]
