# Generated by Django 3.2.16 on 2025-03-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20250301_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingschedule',
            name='food_name',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='food', to='pets.food', verbose_name='Название корма'),
        ),
    ]
