# Generated by Django 3.2.16 on 2025-03-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_feedingschedule_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingschedule',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
