# Generated by Django 3.2.16 on 2025-03-01 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0007_alter_feedingschedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingschedule',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='feedingschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='pets.food', verbose_name='Название корма'),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='next_meal_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ближайшее время кормления'),
        ),
        migrations.AddField(
            model_name='pet',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.food', verbose_name='Используемый корм'),
        ),
        migrations.AlterField(
            model_name='feedingschedule',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_schedule', to='pets.pet', verbose_name='Домашнее животное'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pets.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('М', 'Мальчик'), ('Ж', 'Девочка')], default='М', max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
