# Generated by Django 3.2.16 on 2025-03-01 14:38

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20250301_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_for_breed', to='pets.food'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(validators=[core.validators.real_age], verbose_name='Дата рождения'),
        ),
    ]
