# Generated by Django 3.2.16 on 2025-03-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20250301_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='food',
        ),
        migrations.AddField(
            model_name='breed',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, related_name='food_for_breed', to='pets.Food'),
        ),
    ]
