# Generated by Django 3.2.16 on 2025-03-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_breed_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='size_category',
            field=models.CharField(choices=[('small', 'Мелкая'), ('medium', 'Средняя'), ('large', 'Крупная')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.food', verbose_name='Используемый корм'),
        ),
        migrations.CreateModel(
            name='DailyFeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_feeding_schedule', to='pets.feedingschedule')),
            ],
            options={
                'verbose_name': 'Ежедневное кормление',
                'verbose_name_plural': 'Ежедневные кормления',
            },
        ),
    ]
