# Generated by Django 3.2.16 on 2025-03-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_auto_20250301_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingschedule',
            name='recommended_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_food', to='pets.food', verbose_name='Рекомендуемый корм'),
        ),
        migrations.AddField(
            model_name='food',
            name='sponsored',
            field=models.BooleanField(default=False, verbose_name='Спонсорский корм'),
        ),
    ]
