# Generated by Django 3.2.16 on 2025-03-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_auto_20250301_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='vaccine_name',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Сделана ли прививка'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet', verbose_name='Домашнее животное'),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название вакцины')),
                ('age_in_weeks', models.PositiveIntegerField(verbose_name='Возраст для прививки (в неделях)')),
                ('sponsored', models.BooleanField(default=False, verbose_name='Спонсорская вакцина')),
                ('breeds', models.ManyToManyField(related_name='required_vaccines', to='pets.Breed', verbose_name='Подходящие породы')),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцины',
                'ordering': ['age_in_weeks'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_vaccination_date', models.DateField(blank=True, null=True, verbose_name='Ближайшая дата вакцинации')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedule', to='pets.pet', verbose_name='Домашнее животное')),
                ('recommended_vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='pets.vaccine', verbose_name='Рекомендуемая вакцина')),
            ],
            options={
                'verbose_name': 'График вакцинации',
                'verbose_name_plural': 'Графики вакцинации',
            },
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.vaccine', verbose_name='Вакцина'),
        ),
    ]
