# Generated by Django 3.2.16 on 2025-03-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_auto_20250301_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название болезни')),
                ('common_for_breeds', models.ManyToManyField(blank=True, to='pets.Breed', verbose_name='Часто встречается у пород')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petspecies', verbose_name='Вид животного')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Стерилизовано'),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарства')),
                ('sponsored', models.BooleanField(default=False, verbose_name='Спонсорское лекарство')),
                ('diseases', models.ManyToManyField(related_name='medicines', to='pets.Disease', verbose_name='Лечит болезни')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pets.Disease', verbose_name='Болезни'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pets.Medicine', verbose_name='Принимаемые лекарства'),
        ),
    ]
