# Generated by Django 3.2.16 on 2025-03-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20250301_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='species',
        ),
        migrations.AddField(
            model_name='disease',
            name='species',
            field=models.ManyToManyField(related_name='diseases', to='pets.PetSpecies', verbose_name='Вид животного'),
        ),
    ]
