# Generated by Django 3.2.16 on 2025-03-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_auto_20250301_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedule', to='pets.pet', verbose_name='Домашнее животное'),
        ),
    ]
