# Generated by Django 3.2.16 on 2025-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='cat', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
