# Generated by Django 3.2.16 on 2025-03-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
