# Generated by Django 3.2.16 on 2025-03-01 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Ветеринар',
                'verbose_name_plural': 'Ветеринары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('is_active', models.BooleanField(verbose_name='Предстоящий')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visit', to='pets.pet', verbose_name='Домашнее животное')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visit', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vet_visit', to='vets.veterinarian', verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Посещение ветеринара',
                'verbose_name_plural': 'Посещения ветеринара',
                'ordering': ['-date'],
            },
        ),
    ]
