# Generated by Django 3.2.16 on 2025-03-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название клиники')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='phone',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vets/veterinarians/photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterinarians', to='vets.clinic', verbose_name='Клиника'),
        ),
    ]
