# Generated by Django 3.2.16 on 2025-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_alter_vaccinationschedule_pet'),
        ('vets', '0002_auto_20250313_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='specialties',
            field=models.ManyToManyField(related_name='veterinarians', to='pets.PetSpecies', verbose_name='Специализации'),
        ),
    ]
